### ISSUE TITLE
Should allow specifying threads for callback

### ISSUE THREAD

**Issue by keithtkl** [authgear/authgear-sdk-ios#11]

**Comment by axolotl0212** [comment]
iOS has Grand Central Dispatch. I guess the convention is the caller wrapping the callback body in a desired thread. However, we have to very clear on which thread the callback is invoked. Example of such convention https://developer.apple.com/documentation/avfoundation/avcapturedevice/1624584-requestaccess

doSomething {
  DispatchQueue.main.async {
    // Execute on main thread
  }
}
