### ISSUE TITLE
Variables read/write should be atomic by default

### ISSUE THREAD

**Issue by keithtkl** [authgear/authgear-sdk-ios#13]
shouldRefreshAccessToken can be called in worker thread, and refreshToken etc are read, are variables read/write atomic by default in swift?
https://github.com/authgear/authgear-sdk-ios/blob/master/Sources/Authgear.swift#L110
https://github.com/authgear/authgear-sdk-ios/blob/master/Sources/Authgear.swift#L502

**Comment by axolotl0212** [comment]
variable can be accessed by multiple thread, need to investigate how to protect the variable

**Comment by nicolaslee2775** [comment]
@louischan-oursky Can we wrap `refreshToken` with `ManagedAtomic`? 
https://swift.org/blog/swift-atomics/
