### ISSUE TITLE
Review whether should use make authentication session for open url

### ISSUE THREAD

**Issue by keithtkl** [authgear/authgear-sdk-ios#14]
iOS is using make authentication session for open URL, not sure if this is correct

**Comment by axolotl0212** [comment]
related to #24 ,and PR #25 implemeted the login flow with SFSafariViewController, and handle redirect in AppDelegate. The main function for `ASWebAuthenticationSession` is to handle redirect URL with custom scheme (deep link). If `openUrl` function opens pages which has no redirection with custom scheme (eg. setting page), then it is unnecessary, SFSafariViewController suffice.

**Comment by axolotl0212** [comment]
For both native iOS and react native, will add prefersSafariViewController flag
