### ISSUE TITLE
Find alternative of ASWebAuthenticationSession

### ISSUE THREAD

**Issue by keithtkl** [authgear/authgear-sdk-ios#24]
If we use ASWebAuthenticationSession, there will be an alert with message`{appName} want to use {domain} to sign in ...`, some customers might not want the alert. Hence we want an alternative way to complete auth with Authgear web UI. 

We want the new solution to be able to handle callback from Authgear server

**Comment by axolotl0212** [comment]
Libraries like [AppAuth](https://cocoapods.org/pods/AppAuth) uses built in `SFAuthenticationSession`

According to [RFC8252 section 8.12](https://tools.ietf.org/html/rfc8252#section-8.12), we should not use embedded user-agents, which means we cannot use web-view for this purpose

Use `SFSafariViewController` and [setting custom scheme](https://developer.apple.com/documentation/xcode/allowing_apps_and_websites_to_link_to_your_content/defining_a_custom_url_scheme_for_your_app) (such that we can redirect user back to app) is a possible solution, but we still need to handle the case where user set default browser to Chrome
