### ISSUE TITLE
Create new release and update API reference

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-sdk-ios#93]
- The API reference in https://authgear.github.io/authgear-sdk-ios/ is outdated 
- There is no release since 2020, while the SDK has been changed a lot

**Comment by louischan-oursky** [comment]
I have updated the CI pipeline to deploy the docs on every push to the master branch.

Our user can just point to a particular git commit to use the SDK with Cocoapods. See https://guides.cocoapods.org/using/the-podfile.html and search for "specify a commit"

**Comment by fungc-io** [comment]
![image](https://user-images.githubusercontent.com/15207470/210306457-2600a9f5-21a2-46e3-ab6e-be612b3ff51a.png)

These make it feels like the doc is very outdated
Any suggestion to reflect the actual version?

**Comment by louischan-oursky** [comment]
https://github.com/authgear/authgear-sdk-ios/commit/6783792be30a6e07d54d68c3e8ca9a918b03b8bc
