### ISSUE TITLE
ios sdk cancel should be after dismiss

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-sdk-ios#98]

**Comment by kiootic** [comment]
I think as discussed, we will keep calling the completion callback right after start dismiss. If developers would like to perform actions after dismissal is completed, they can do it in `viewDidAppear` of the presenting view controller.

cc @louischan-oursky

**Comment by fungc-io** [comment]
will not be fixed in our public SDK. If such use case, customization should be required.
